version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: "${POSTGRES_CONTAINER_NAME}"
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  mongo:
    image: mongo:6
    container_name: "${MONGO_CONTAINER_NAME}"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodata:/data/db
    networks:
      - backend

volumes:
  pgdata:
  mongodata:

networks:
  backend:
